### ISSUE TITLE
希望能像Butterfly那样支持插入</head>

### ISSUE THREAD

**Issue by LynxCatTheThird** [argvchs/hexo-theme-particlex#32]
因为[哔哩哔哩图床](https://daiyu-233.top/posts/9bf9.html)的需要，必须在所有的html的</head>中插入一行，但这项工程明显十分繁琐。希望能像Butterfly那样批量导入</head>

**Comment by argvchs** [comment]
批量导入？？
直接在 `layout.ejs` 加就行

**Comment by argvchs** [comment]
可能写成参数的更好维护？
有时间再写吧

**Comment by LynxCatTheThird** [comment]
谢谢了

**Comment by argvchs** [comment]
有一篇用 MathJax 渲染的
<https://argvchs.netlify.app/2022/06/17/hexo-latex/>

KaTeX 不会。。

**Comment by LynxCatTheThird** [comment]
C:\Users\LynxCatTheThird\web\person>hexo s
INFO  Validating config
INFO  Start processing
FATAL {
  err: Error:
  [ERROR][hexo-renderer-pandoc] On C:\Users\LynxCatTheThird\web\person\source\_posts\top.md
  [ERROR][hexo-renderer-pandoc] pandoc exited with code null.
      at Hexo.pandocRenderer (C:\Users\LynxCatTheThird\web\person\node_modules\hexo-renderer-pandoc\index.js:119:11)
      at Hexo.tryCatcher (C:\Users\LynxCatTheThird\web\person\node_modules\bluebird\js\release\util.js:16:23)
      at Hexo.<anonymous> (C:\Users\LynxCatTheThird\web\person\node_modules\bluebird\js\release\method.js:15:34)
      at C:\Users\LynxCatTheThird\web\person\node_modules\hexo\lib\hexo\render.js:75:22
      at tryCatcher (C:\Users\LynxCatTheThird\web\person\node_modules\bluebird\js\release\util.js:16:23)
      at Promise._settlePromiseFromHandler (C:\Users\LynxCatTheThird\web\person\node_modules\bluebird\js\release\promise.js:547:31)
      at Promise._settlePromise (C:\Users\LynxCatTheThird\web\person\node_modules\bluebird\js\release\promise.js:604:18)
      at Promise._settlePromiseCtx (C:\Users\LynxCatTheThird\web\person\node_modules\bluebird\js\release\promise.js:641:10)
      at _drainQueueStep (C:\Users\LynxCatTheThird\web\person\node_modules\bluebird\js\release\async.js:97:12)
      at _drainQueue (C:\Users\LynxCatTheThird\web\person\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\Users\LynxCatTheThird\web\person\node_modules\bluebird\js\release\async.js:102:5)
      at Async.drainQueues [as _onImmediate] (C:\Users\LynxCatTheThird\web\person\node_modules\bluebird\js\release\async.js:15:14)
      at process.processImmediate (node:internal/timers:471:21)
} Something's wrong. Maybe you can find the solution here: %s https://hexo.io/docs/troubleshooting.html
😢
